import React from 'react'
import styles from '../styles/Login.module.css'
import Head from 'next/head'

export default function Login() {
    return (
        <div>
            <Head>
                <title>Login | Track Your Location</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.form}>
                    <h3>Silahkan Login</h3>
                    <div>
                        <label for="fname">Email</label><br/>
                        <input type="text" id="fname" name="fname"/><br/>
                        <label for="lname">Password</label><br/>
                        <input type="text" id="lname" name="lname"/><br/><br/>
                        <input type="submit" value="Submit" />
                    </div> 
                </div>
            </main>
        </div>
    )
}
